openapi: 3.0.0
info:
  version: 1.0.0
  title: Reto tecnico INDRA
servers:
- url: '{server}/dev'
  variables:
    server:
      default: https://nb5ghd88r3.execute-api.us-east-1.amazonaws.com
tags:
- name: swapi
  description: Operaciones swapi
- name: mysql
  description: Operaciones mysql
paths:
  "/obtener-persona-por-id":
    get:
      tags:
      - swapi
      summary: Obtener persona swapi
      parameters:
        - in: query
          name: id
          schema:
            type: integer
          required: true
          description: Id de persona
      responses:
        '200':    # status code
          description: Datos encontrados correctamente
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/swapiResponse"
        '400':
          description: Error parametros de envio invalidos.
        '500':
          description: Error del Servidor
  "/guardar-persona":
    post:
      tags:
      - mysql
      summary: Guardar persona mysql
      requestBody:
        description: Json Solicitud
        required: true
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/personaRequest"
      responses:
        '200':    # status code
          description: Datos encontrados correctamente
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/personaResponse"
        '400':
          description: Error parametros de envio invalidos.
        '500':
          description: Error del Servidor
  "/paginar-personas":
    get:
      tags:
      - mysql
      summary: Paginar personas mysql
      parameters:
        - in: query
          name: pagina
          schema:
            type: integer
          required: true
          description: Página actual
        - in: query
          name: limite
          schema:
            type: integer
          required: true
          description: Límite de registros
      responses:
        '200':    # status code
          description: Datos encontrados correctamente
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/personasResponse"
        '400':
          description: Error parametros de envio invalidos.
        '500':
          description: Error del Servidor
components:
  schemas:
    swapiResponse:
      type: object
      properties:
        nombre:
          type: string
          format: string
          example: 175
        altura:
          type: string
          format: string
          example: rulman
        masa:
          type: string
          format: string
          example: 94
        colorPelo:
          type: string
          format: string
          example: rojo
        colorPiel:
          type: string
          format: string
          example: blanca
        colorOjo:
          type: string
          format: string
          example: verde
        fechaNacimiento:
          type: string
          format: string
          example: 26/07/1990
        genero:
          type: string
          format: string
          example: M
    personaRequest:
        type: object
        properties:
          nombre:
            type: string
            format: string
            example: 175
          altura:
            type: string
            format: string
            example: rulman
          masa:
            type: string
            format: string
            example: 94
          colorPelo:
            type: string
            format: string
            example: rojo
          colorPiel:
            type: string
            format: string
            example: blanca
          colorOjo:
            type: string
            format: string
            example: verde
          fechaNacimiento:
            type: string
            format: string
            example: 26/07/1990
          genero:
            type: string
            format: string
            example: M
    personaResponse:
      type: object
      properties:
        id:
          type: string
          format: string
          example: 40f9bdfd-b430-11ec-b60e-02f757bd4c9b
        message:
          type: string
          format: string
          example: Persona Registrada
        code:
          type: string
          format: string
          example: 200
    personasResponse:
        type: object
        properties:
          registros:
            type: integer
            format: integer
            example: 10
          pagina:
            type: integer
            format: integer
            example: 0
          colaboradores:
            type: array
            items:
              type: object
              properties:
                nombre:
                  type: string
                  format: string
                  example: 175
                altura:
                  type: string
                  format: string
                  example: rulman
                masa:
                  type: string
                  format: string
                  example: 94
                colorPelo:
                  type: string
                  format: string
                  example: rojo
                colorPiel:
                  type: string
                  format: string
                  example: blanca
                colorOjo:
                  type: string
                  format: string
                  example: verde
                fechaNacimiento:
                  type: string
                  format: string
                  example: 26/07/1990
                genero:
                  type: string
                  format: string
                  example: M