
  
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: servicios fernet agencia
Globals:
  Function:
    Timeout: 600
    Runtime: nodejs14.x
    MemorySize: 1024
    Architectures:
      - x86_64
    Environment:
      Variables:
        MONGO_URI: mongodb+srv://k4p:Rulman26@k4p-z7qkz.mongodb.net/agenciaDev?retryWrites=true&w=majority
  Api:
    Cors:
      AllowMethods: "'POST, GET, OPTIONS'"
      AllowHeaders: "'*'"
      AllowOrigin: "'*'"
      AllowCredentials: false
Parameters:
  Stage:
    Type: String
    Default: dev
Resources:
  getPeopleById:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: ./functions
      Handler: app.getPeopleById
      Events:
        getPeopleById:
          Type: Api 
          Properties:
            RestApiId: !Ref IndraApi
            Path: /people-by-id
            Method: get
  IndraApi:
      Type: AWS::Serverless::Api
      Properties:
        StageName: !Ref Stage
        Auth:
          ApiKeyRequired: false
Outputs:
  AgenciaApi:
    Description: "API Gateway endpoint URL for ${Stage} stage"
    Value: !Sub "https://${IndraApi}.execute-api.${AWS::Region}.amazonaws.com/${Stage}"