
  
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: servicios fernet agencia
Globals:
  Function:
    Timeout: 600
    Runtime: nodejs14.x
    MemorySize: 1024
    Architectures:
      - x86_64
    Environment:
      Variables:
        MYSQL_HOST: xxxxxxxxx
        MYSQL_DATABASE: indra
        MYSQL_USER: admin
        MYSQL_PASSWORD: xxxxxxxxx
        MYSQL_CONNECTION_LIMIT: 10
        MYSQL_QUEUE_LIMIT: 10
  Api:
    Cors:
      AllowMethods: "'POST, GET, OPTIONS'"
      AllowHeaders: "'*'"
      AllowOrigin: "'*'"
      AllowCredentials: false
Parameters:
  Stage:
    Type: String
    Default: dev
Resources:
  obtenerPersonaPorId:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: ./functions
      Handler: app.obtenerPersonaPorId
      Events:
        obtenerPersonaPorId:
          Type: Api 
          Properties:
            RestApiId: !Ref IndraApi
            Path: /obtener-persona-por-id
            Method: get
  guardarPersona:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: ./functions
      Handler: app.guardarPersona
      Events:
        guardarPersona:
          Type: Api 
          Properties:
            RestApiId: !Ref IndraApi
            Path: /guardar-persona
            Method: post
  paginarPersonas:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: ./functions
      Handler: app.paginarPersonas
      Events:
        paginarPersonas:
          Type: Api 
          Properties:
            RestApiId: !Ref IndraApi
            Path: /paginar-personas
            Method: get
  IndraApi:
      Type: AWS::Serverless::Api
      Properties:
        StageName: !Ref Stage
        Auth:
          ApiKeyRequired: false
Outputs:
  AgenciaApi:
    Description: "API Gateway endpoint URL for ${Stage} stage"
    Value: !Sub "https://${IndraApi}.execute-api.${AWS::Region}.amazonaws.com/${Stage}"